# Generated by Django 4.1.4 on 2022-12-10 23:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0002_contactticekts'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactTicekts',
            new_name='ContactTickets',
        ),
    ]
