# Generated by Django 4.1.4 on 2022-12-10 23:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('contact', '0003_rename_contactticekts_contacttickets'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='ContactTickets',
            new_name='ContactTicket',
        ),
    ]
