# Generated by Django 4.1.4 on 2022-12-08 23:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='collectionproduct',
            name='photo',
            field=models.ImageField(blank=True, upload_to='collection'),
        ),
        migrations.AlterField(
            model_name='heroproduct',
            name='photo',
            field=models.ImageField(blank=True, upload_to='hero'),
        ),
    ]
