# Generated by Django 4.1.4 on 2022-12-09 00:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0002_alter_collectionproduct_photo_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
    ]
