# Generated by Django 4.1.4 on 2022-12-09 00:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0003_featuredproduct_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='featuredproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='feature'),
        ),
    ]
