# Generated by Django 4.1.4 on 2022-12-09 12:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0004_featuredproduct_image'),
    ]

    operations = [
        migrations.RenameField(
            model_name='collectionproduct',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='heroproduct',
            old_name='photo',
            new_name='image',
        ),
        migrations.RenameField(
            model_name='promoproduct',
            old_name='promo_end_date',
            new_name='end_date',
        ),
        migrations.RenameField(
            model_name='promoproduct',
            old_name='promo_start_date',
            new_name='start_date',
        ),
        migrations.RenameField(
            model_name='saleproduct',
            old_name='sale_date',
            new_name='date',
        ),
        migrations.RenameField(
            model_name='saleproduct',
            old_name='sale_detail',
            new_name='detail',
        ),
        migrations.RemoveField(
            model_name='promoproduct',
            name='promo_image',
        ),
        migrations.RemoveField(
            model_name='saleproduct',
            name='sale_image',
        ),
        migrations.AddField(
            model_name='promoproduct',
            name='image',
            field=models.ImageField(blank=True, upload_to='promo'),
        ),
        migrations.AddField(
            model_name='saleproduct',
            name='imade',
            field=models.ImageField(blank=True, upload_to='sale'),
        ),
    ]
