# Generated by Django 4.1.4 on 2022-12-09 12:54

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0005_rename_photo_collectionproduct_image_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='saleproduct',
            old_name='imade',
            new_name='image',
        ),
    ]
