# Generated by Django 4.1.4 on 2022-12-10 22:28

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('about', '0002_aboutcomponent_available'),
    ]

    operations = [
        migrations.AlterField(
            model_name='aboutcomponent',
            name='video',
            field=models.FileField(blank=True, null=True, upload_to='about/video', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['MOV', 'avi', 'mp4', 'webm', 'mkv'])]),
        ),
    ]
